import { StyleSheet } from 'react-native';//全球流呼叫CSS*

export const GWStyles = StyleSheet.create({

    container: {
        resizeMode:'contain',
        justifyContent:'center',
        flex:1,
    },
    container1:{  
    height: "75%",
    width: "100%",
    top:'24%',
    position: 'absolute',
    //backgroundColor:"#d9cfc5",
    fontFamily:'nunito-bold',
    //marginVertical:'5%',
    color:'#333',
    justifyContent: 'center',
    //marginBottom:'15%',
  },
    container2: {
        resizeMode:'contain',
        flex:1,
    },
    imagesize:{
        height:"100%",
        width:"100%",
        resizeMode:'stretch',
    },
    backbutton: {
    resizeMode:'stretch',
    width: "8%", 
    height: "7%",
    left:'5%',
    top:"6.5%",
    //bottom:'0%' ,
    position: 'absolute',
    //backgroundColor:'#333',
  },
  GW_Card:{  
    height:"100%",
    width:"100%",
    fontFamily:'nunito-bold',
    //marginVertical:'5%',
    //justifyContent: 'center',
    //marginBottom:'10%',
    //backgroundColor:'#d9cfc5',
  },
  login_image: {
        width:'100%',
        height:'100%',
        flex: 1,
        justifyContent: "center",
      },
  AnnounceCard:{  
    height:"76%",
    width:"100%",
    top:'11%',
    fontFamily:'nunito-bold',
    //marginVertical:'5%',
    color:'#333',
    //justifyContent: 'center',
    //marginBottom:'10%',
    //backgroundColor:'#d9cfc5',
  },
    GW_Box:{  
    fontFamily:'nunito-bold',
    borderRadius:15,
    marginVertical:"2.5%",
    textAlign: 'center',
    color:'#333',
    shadowOffset:{width:1,height:1},
    shadowRadius:2,
    shadowOpacity:6,
    elevation:3,
    backgroundColor:'#fbd292',
    height:300,
    width:"70%",
    left:'15%',
    //borderWidth: 1,
  },  
  toptext2:{  
    fontFamily:'nunito-bold',
    borderRadius:30,
    marginVertical:"2.5%",
    textAlign: 'center',
    color:'#333',
    shadowOffset:{width:1,height:1},
    shadowRadius:2,
    shadowOpacity:6,
    elevation:3,
    backgroundColor:'#fce9de',
    height:600,
    width:"75%",
    left:'12.5%',
  },  
  CardBox:{ 
    top:"20%", 
    left:'6%',
    height:'75%',
    width:'88%', 
    marginVertical:"-2.5%",
    borderRadius:15,
  },
  CardBox2:{  
    //top:'25%',
    left:'15%',
    height:250,
    width:'70%', 
    marginVertical:'2%',
    backgroundColor:'#fbfadf',
    //position: 'absolute',
  },
  image:{
    height:'100%',
    width:'100%', 
    borderRadius:3,
    resizeMode:'stretch',
  },
  image2:{
    height:'100%',
    width:'100%', 
    borderRadius:3,
    resizeMode:'stretch',
  },
  GWTitlebox:{
    height:'15%',
    width:'50%', 
    //backgroundColor:'#fce9de',
    position: 'absolute',
    justifyContent:'center',
    textAlign: 'center',
    alignItems:'center',
  },
    GWTimebox:{
    height:'15%',
    width:'50%', 
    left:"50%",
    //backgroundColor:'#fce9de',
    position: 'absolute',
    justifyContent:'center',
    textAlign: 'center',
    alignItems:'center',
  },
  GWTitle:{  
    fontFamily:'nunito-bold',
    fontSize: 22,

  },  
  GWTime:{  
    fontFamily:'nunito-bold',
    fontSize: 20,
  },  
  AnnounTitle2:{  
    fontFamily:'nunito-bold',
    fontSize: 25,
    //marginVertical:'1%',
    marginHorizontal:'5%',
    textAlign: 'center',
  },  
  AnnounDate:{
    fontFamily:'nunito-bold',
    fontSize: 15,
    //marginVertical:'5%',
    justifyContent: 'center',
    marginHorizontal:'5%',
  },
  AnnounContent:{
    fontFamily:'nunito-bold',
    fontSize: 25,
    left:'10%',
    width:'80%', 
    //marginVertical:'5%',
    justifyContent: 'center',
    //backgroundColor:'#fce9de',
  },
});