import { StyleSheet } from 'react-native';

export const Gallery = StyleSheet.create({  
    background: {
      flex:1,
      backgroundColor:'#ffffff',
      },
      container: {
    resizeMode:'contain',
    justifyContent:'center',
    flex:1,
  },
  upperspace:{
        width: '100%', 
         height: '10%',
         marginBottom:'5%'
        },
 backbutton: {
    resizeMode:'stretch',
    width: "10%", 
    height: "90%",
    top:'80%',
    left:'2%',
    //bottom:'0%' ,
    position: 'absolute',
  },
  back: {
   width: "100%", 
   height: "100%",
   resizeMode:'stretch',
  },
  container1:{  
    top:'10%',
    fontFamily:'nunito-bold',
    //marginVertical:'5%',
    color:'#333',
    justifyContent: 'center',
    marginBottom:'15%',
  },
  container2:{  
    top:'15%',
    fontFamily:'nunito-bold',
    //marginVertical:'5%',
    color:'#333',
    justifyContent: 'center',
    marginBottom:'15%',
  },
  Title:{  
    fontSize: 25,
    //marginVertical:'5%',
    justifyContent: 'center',
    marginHorizontal:'5%',
  },
   Contents:{
    
    fontSize: 15,
    //marginVertical:'2%',
    marginHorizontal:'5%',
  },

  CardBox:{  
        height:280,
        width:"80%",
        marginHorizontal:"10%",
        backgroundColor:"#d9cfc5",
        borderRadius:10,
        elevation:10,
        marginVertical:"2.5%",
        //alignItems:'center',
        //padding:15,
  },
  CardBox2:{  
    top:'25%',
    left:'5%',
    fontFamily:'nunito-bold',
    //fontSize: 30,
    //borderRadius:30,
    //marginVertical:"20%",
    textAlign: 'center',
    color:'#fbfadf',
    //shadowOffset:{width:1,height:1},
    //shadowRadius:2,
    //shadowOpacity:6,
    //elevation:3,
    backgroundColor:'#fbfadf',
    justifyContent: 'center',
    //marginHorizontal:"20%",
    height:200,
    width:'45%', 
    position: 'absolute',
  },
  CardBox3:{  
    top:'25%',
    left:'55%',
    fontFamily:'nunito-bold',
    textAlign: 'center',
    color:'#fbfadf',
    backgroundColor:'#333',
    justifyContent: 'center',
    height:100,
    width:'40%', 
    position: 'absolute',
  },
  CardBox4:{  
    top:'60%',
    left:'55%',
    fontFamily:'nunito-bold',
    textAlign: 'center',
    color:'#fbfadf',
    backgroundColor:'#fbfadf',
    justifyContent: 'center',
    height:100,
    width:'40%', 
    position: 'absolute',
  },
  Photos: {
  resizeMode:'stretch',
  height:'100%',
  width: '100%',
   
  },
  Photos2: {
  resizeMode:'stretch',
  height:'125%',
  width: '100%',
   
  },

    controlBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 145,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  OverFlow:{
    textAlign: 'center',
    alignItems: 'center',
    fontSize: 30,
  },
  Bigimage:{
      flex:1,
      backgroundColor:'#333',
      textAlign: 'center',
      alignItems: 'center',
      height:500,
      width:500,
  },
    imgBox:{  
        height:"100%",
        width:"80%",
        marginHorizontal:"10%",
        backgroundColor:"#d9cfc5",
        borderRadius:10,
        elevation:10,
        marginVertical:"2.5%",
        //alignItems:'center',
        //padding:15,
  },
  imgBox2:{  
        //height:"100%",
        width:"80%",
        marginHorizontal:"10%",
        backgroundColor:"#fbfadf",
        borderRadius:10,
        elevation:10,
        marginVertical:"2.5%",
        //alignItems:'center',
        //padding:15,
  },
  Rec:{  
    fontSize: 20,
    //marginVertical:'5%',
    justifyContent: 'center',
    //alignItems:'center',
    marginHorizontal:'7.5%',
  },

    });