import { StyleSheet } from 'react-native';

export const Gallery = StyleSheet.create({  
    background: {
      flex:1,
      backgroundColor:'#ffffff',
      },
      container: {
    resizeMode:'contain',
    justifyContent:'center',
    flex:1,
  },
        login_image: {
        width:'100%',
        height:'100%',
        flex: 1,
        justifyContent: "center",
      },
    backbutton: {
    resizeMode:'stretch',
    width: "8%", 
    height: "7%",
    left:'5%',
    top:"6.5%",
    //bottom:'0%' ,
    position: 'absolute',
    //backgroundColor:'#333',
  },
    backbutton2: {
    resizeMode:'stretch',
    width: "12%", 
    height: "7%",
    left:'85%',
    top:"6.5%",
    //bottom:'0%' ,
    position: 'absolute',
    //backgroundColor:'#333',
  },
  back: {
   width: "100%", 
   height: "100%",
   resizeMode:'stretch',
  },
   R_backbutton:{
    resizeMode:'stretch',
    width: "8%", 
    height: "7%",
    left:'5%',
    top:"6.5%",
    //bottom:'0%' ,
    position: 'absolute',
    //backgroundColor:'#333',
  },
  R_back: {
   width: "100%", 
   height: "100%",
   resizeMode:'stretch',
  },
  container1:{  
    height: "72%",
    width: "100%",
    top:'25%',
    position: 'absolute',
    //backgroundColor:"#d9cfc5",
    fontFamily:'nunito-bold',
    //marginVertical:'5%',
    color:'#333',
    justifyContent: 'center',
    //marginBottom:'15%',
  },
  container2:{  
    height: "78%",
    width: "100%",
    top:'20%',
    position: 'absolute',
    fontFamily:'nunito-bold',
    //marginVertical:'5%',
    color:'#333',
    justifyContent: 'center',
    //marginBottom:'17%',
    //backgroundColor:"#d9cfc5",
  },
  Title:{  
    fontSize: 20,
  },
   Contents:{
    fontSize: 20,
  },
  Title2:{  
    fontSize: 25,
    marginHorizontal:"5%",
  },
  CardBox:{  
        //top:"10%",
        height:280,
        width:"80%",
        marginHorizontal:"10%",
        backgroundColor:"#fbd292",
        borderRadius:10,
        elevation:10,
        marginVertical:"2.5%",
        opacity: 0.9,
        //alignItems:'center',
        //padding:15,
  },
  CardBox2:{  
    top:'32.5%',
    left:'5%',
    fontFamily:'nunito-bold',
    //fontSize: 30,
    //borderRadius:30,
    //marginVertical:"20%",
    textAlign: 'center',
    color:'#fbfadf',
    //shadowOffset:{width:1,height:1},
    //shadowRadius:2,
    //shadowOpacity:6,
    //elevation:3,
    backgroundColor:'#fbfadf',
    justifyContent: 'center',
    //marginHorizontal:"20%",
    height:'60%',
    width:'45%', 
    position: 'absolute',
  },
  CardBox3:{  
    top:'32.5%',
    left:'55%',
    fontFamily:'nunito-bold',
    textAlign: 'center',
    color:'#fbfadf',
    backgroundColor:'#fbfadf',
    justifyContent: 'center',
    height:'30%',
    width:'40%', 
    position: 'absolute',
  },
  CardBox4:{  
    top:'62.5%',
    left:'55%',
    fontFamily:'nunito-bold',
    textAlign: 'center',
    color:'#fbfadf',
    backgroundColor:'#fbfadf',
    justifyContent: 'center',
    alignItems: 'center',
    height:'30%',
    width:'40%', 
    position: 'absolute',
  },
    CardBox5:{  
    top:'17.5%',
    left:'5%',
    fontFamily:'nunito-bold',
    textAlign: 'center',
    color:'#fbfadf',
    //backgroundColor:'#fbfadf',
    justifyContent: 'center',
    //alignItems: 'center',
    height:'12.5%',
    width:'90%', 
    position: 'absolute',
  },
    CardBox6:{  
    top:'2.5%',
    left:'5%',
    fontFamily:'nunito-bold',
    textAlign: 'center',
    color:'#fbfadf',
    //backgroundColor:'#fbfadf',
    justifyContent: 'center',
    //alignItems: 'center',
    height:'12.5%',
    width:'90%', 
    position: 'absolute',
  },
    CardBox7:{  
    top:'5%',
    left:'5%',
    fontFamily:'nunito-bold',
    textAlign: 'center',
    color:'#fbfadf',
    backgroundColor:'#fbd292',
    justifyContent: 'center',
    height:'90%',
    width:'90%', 
    opacity: 0.9,
    position: 'absolute',
    borderRadius:10,
  },
    RecordBox:{  
        height:220,
        width:"80%",
        marginHorizontal:"10%",
        //backgroundColor:"#d9cfc5",
        borderRadius:10,
        elevation:10,
        marginVertical:"2.5%",
        //alignItems:'center',
        //padding:15,
  },
  Photos: {
  resizeMode:'stretch',
  height:'100%',
  width: '100%',
  position: 'absolute',
  },
  Photos2: {
  resizeMode:'stretch',
  height:220,
  width: '100%',
   
  },

    controlBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 145,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  OverFlow:{
    fontFamily:'nunito-bold',
    textAlign: 'center',
    alignItems: 'center',
    fontSize: 30,
    //backgroundColor: "#333",
    //position: 'absolute',
  },
  Bigimage:{
      flex:1,
      backgroundColor:'#333',
      textAlign: 'center',
      alignItems: 'center',
      height:500,
      width:500,
  },
    imgBox:{  
        height:"100%",
        width:"80%",
        marginHorizontal:"10%",
        backgroundColor:"#d9cfc5",
        borderRadius:10,
        elevation:10,
        marginVertical:"2.5%",
        //alignItems:'center',
        //padding:15,
  },
  imgBox2:{  
        //height:"100%",
        width:"80%",
        marginHorizontal:"10%",
        backgroundColor:"#fbfadf",
        borderRadius:10,
        elevation:10,
        marginVertical:"2.5%",
        //alignItems:'center',
        //padding:15,
  },
  Rec:{  
    fontSize: 25,
    //marginVertical:'5%',
    justifyContent: 'center',
    //alignItems:'center',
    marginHorizontal:'7.5%',
  },
  Rec2:{  
    fontSize: 20,
    top:"1%",
    justifyContent: 'center',
    //alignItems:'center',
    marginHorizontal:'5%',
  },

    });