import { StyleSheet } from 'react-native';//全球流呼叫CSS*

export const Globalstyles = StyleSheet.create({
  container: {
    resizeMode:'contain',
    justifyContent:'center',
    flex:1,
  },
  text:{
        elevation:30,
        justifyContent:'center',
        alignItems: 'center',
        textAlign: 'center',

  },
  centerbotton:{
        height:"5%",
        width:"25%",
        backgroundColor:"#FBFADF",
        borderRadius:20,
        elevation:30,
        justifyContent:'center',
        textAlign: 'center',
        alignItems:'center',
  },
  toptext:{  
        fontFamily:'nunito-bold',
        fontSize: 15,
        //borderRadius:50,
        marginVertical:10,
        //alignItems: 'center',
        //textAlign: 'center',
        color:'#333',
        //shadowOffset:{width:1,height:1},
        //shadowRadius:2,
        //shadowOpacity:6,
        //elevation:3,
        //backgroundColor:'#fbfadf',
        //width:'75%',
        //height:'50%',
        justifyContent: 'center',
        marginHorizontal:25,
        top:'1%',

  },  
  toptext5:{  
        top:'5%',
        fontFamily:'nunito-bold',
        //fontSize: 15,
        //borderRadius:50,
        marginVertical:'5%',
        //alignItems: 'center',
        //textAlign: 'center',
        color:'#333',
        //shadowOffset:{width:1,height:1},
        //shadowRadius:2,
        //shadowOpacity:6,
        //elevation:3,
        //backgroundColor:'#d9cfc5',
        //width:'75%',
        //height:'50%',
        justifyContent: 'center',
        //marginHorizontal:25,
        marginBottom:'5%',

  },
  
    toptext3:{  
        fontFamily:'nunito-bold',
        fontSize: 30,
        //borderRadius:50,
        //marginVertical:20,
        //alignItems: 'center',
        //textAlign: 'center',
        color:'#333',
        //shadowOffset:{width:1,height:1},
        //shadowRadius:2,
        //shadowOpacity:6,
        //elevation:3,
        //backgroundColor:'#d9cfc5',
        //width:'75%',
        //height:'50%',
        justifyContent: 'center',
        marginHorizontal:25,

  },
    toptext2:{  
        fontFamily:'nunito-bold',
        fontSize: 15,
        //borderRadius:50,
        marginVertical:10,
        //alignItems: 'center',
        //textAlign: 'center',
        color:'#333',
        //shadowOffset:{width:1,height:1},
        //shadowRadius:2,
        //shadowOpacity:6,
        //elevation:3,
        //backgroundColor:'#d9cfc5',
        //width:'75%',
        //height:'50%',
        justifyContent: 'center',
        marginHorizontal:25,

  },
    toptext1:{  
        fontFamily:'nunito-bold',
        fontSize: 30,
        borderRadius:30,
        marginVertical:10,
        //alignItems: 'center',
        textAlign: 'center',
        color:'#333',
        shadowOffset:{width:1,height:1},
        shadowRadius:2,
        shadowOpacity:6,
        elevation:3,
        backgroundColor:'#d9cfc5',
        width:'75%',
        
        justifyContent: 'center',
        marginHorizontal:50,

  },
    titletext:{  
      //flex: 1,
        fontFamily:'nunito-bold',
        fontSize: 30,
        //borderRadius:50,
       // marginVertical: 50,
        alignItems: 'center',
        textAlign: 'center',
        justifyContent: "center",
        color:'#333',
        //backgroundColor:'#d9cfc5',
  },
  test1:{
    padding:10,
  },
  paragraph:{
      marginVertical:8,
      lineHeight:20,
  },
  title:{
    //flex: 1,
    resizeMode:'contain',
    //alignItems: 'center',
    marginHorizontal:"2%",
    marginVertical:'15%' ,
    //backgroundColor: "#d9cfc5",
    //justifyContent: "center",
    //backgroundSize:"50%",
  },
    Background: {
        width:'100%',
        height:'100%',
        flex: 1,
        justifyContent: "center",
        resizeMode:'stretch',
      },
});